require 'rubygems/package_task'

spec = Gem::Specification.new do |s|
	s.name = 'anagram'
	s.summary = 'Find anagrams of words supplied on the command line'
	s.description = File.read(File.join(File.dirname(__FILE__), 'README'))
	s.requirements = ['An installed dicitonary (most Unix systems have one)']
	s.version = '0.0.1'
	s.author = 'Lan Do'
	s.email = 'tuonglan7777777@yahoo.com'
	s.homepage = 'http://www.github.com/lando'
	s.required_ruby_version = '>=2.3'
	s.files = Dir['**/**']
	s.executables = ['anagram']
	s.test_files = Dir["test/test*.rb"]
	s.has_rdoc = false
end


Gem::PackageTask.new(spec) do |pkg|
	pkg.need_zip = true
	pkg.need_tar = true
end
