name 'motd-attributes'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures motd-attributes'
long_description 'Installs/Configures motd-attributes'
version '0.1.0'
