---
driver:
  name: ec2
  aws_ssh_key_id: Amazone - Chef
  security_group_ids: ["sg-d9e184b0"]
  region: ap-northeast-2
  availability_zone: a
  require_chef_omnibus: true
  instance_type: t2.micro
  associate_public_ip: true
  shared_credentials_profile: AWS

provisioner:
  name: shell

platforms:
  - name: ubuntu-hc-aws0
    driver:
        image_id: ami-09dc1267
        synced_folders:
            - ["../../../chef-repo", "/chef-repo"]
    transport:
        ssh_key: /home/lando/.ssh/AWS.pem
        username: ubuntu

suites:
  - name: node
    attributes:
